"""Create Idea model

Revision ID: 3c325dc3268f
Revises: 12d6af54e5d3
Create Date: 2023-07-23 23:19:58.971459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c325dc3268f'
down_revision = '12d6af54e5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=250), nullable=False),
    sa.Column('type', sa.String(length=250), nullable=False),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('link', sa.String(length=250), nullable=True),
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('accessibility', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('idea')
    # ### end Alembic commands ###
